FLIPKART_OCCASION_MAPPING = {
    "Bridal Saree": "Wedding & Festive",
    "Celebrity Inspired": "Party",
    "Daily": "Casual",
    "Farewell": "Party",
    "Party": "Party",
    "Traditional": "Festive",
    "Wedding": "Wedding",
    "Party & Festive": "Party & Festive",
}

MEESHO_OCCASION_MAPPING = {
    "Bridal Saree": "Bridal Saree",
    "Celebrity Inspired": "Celebrity Inspired",
    "Daily": "Daily",
    "Farewell": "Farewell",
    "Party": "Party",
    "Traditional": "Traditional",
    "Wedding": "Wedding",
    "Party & Festive": "Party",
}


# FLIPKART_COLOR_MAPPING = {
#     "Mehendi": "Light Green",
#     "Beige": "Beige",
#     "Black": "Black",
#     "Blue": "Blue",
#     "Navy Blue": "Blue",
#     "Brown": "Brown",
#     "Cream": "Cream",
#     "Dark Blue": "Dark Blue",
#     "Dark Green": "Dark Green",
#     "Gold": "Gold",
#     "Green": "Green",
#     "Grey": "Grey",
#     "Light Blue": "Light Blue",
#     "Light Green": "Light Green",
#     "Magenta": "Magenta",
#     "Maroon": "Maroon",
#     "Multicolor": "Multicolor",
#     "Mustard": "Mustard",
#     "Orange": "Orange",
#     "Pink": "Pink",
#     "Purple": "Purple",
#     "Red": "Red",
#     "Silver": "Silver",
#     "White": "White",
#     "Yellow": "Yellow",
# }

FLIPKART_COLOR_MAPPING = {
    # Direct matches
    "Beige": "Beige",
    "Black": "Black",
    "Blue": "Blue",
    "Brown": "Brown",
    "Cream": "Cream",
    "Gold": "Gold",
    "Green": "Green",
    "Grey": "Grey",
    "Maroon": "Maroon",
    "Multicolor": "Multicolor",
    "Mustard": "Mustard",
    "Orange": "Orange",
    "Pink": "Pink",
    "Purple": "Purple",
    "Red": "Red",
    "Silver": "Silver",
    "White": "White",
    "Yellow": "Yellow",

    # Best-fit mappings
    "Aqua Blue": "Light Blue",
    "Coral": "Pink",
    "Grey Melange": "Grey",
    "Khaki": "Brown",
    "Lavender": "Purple",
    "Mehendi": "Light Green",
    "Metallic": "Silver",   # or "Gold" depending on product
    "Navy Blue": "Dark Blue",
    "Nude": "Beige",
    "Olive": "Dark Green",
    "Peach": "Pink",
    "Rust": "Brown",
    "Teal": "Blue",
    "Dark Blue": "Dark Blue",
    "Dark Green": "Dark Green",
    "Light Blue": "Light Blue",
    "Light Green": "Light Green",
    "Magenta": "Magenta",
}

MEESHO_COLOR_MAPPING = {
   "Aqua Blue": "Aqua Blue",
    "Beige": "Beige",
    "Black": "Black",
    "Blue": "Blue",
    "Brown": "Brown",
    "Coral": "Coral",
    "Cream": "Cream",
    "Gold": "Gold",
    "Green": "Green",
    "Grey": "Grey",
    "Grey Melange": "Grey Melange",
    "Khaki": "Khaki",
    "Lavender": "Lavender",
    "Maroon": "Maroon",
    "Mehendi": "Mehendi",
    "Metallic": "Metallic",
    "Multicolor": "Multicolor",
    "Mustard": "Mustard",
    "Navy Blue": "Navy Blue",
    "Nude": "Nude",
    "Olive": "Olive",
    "Orange": "Orange",
    "Peach": "Peach",
    "Pink": "Pink",
    "Purple": "Purple",
    "Red": "Red",
    "Rust": "Rust",
    "Silver": "Silver",
    "Teal": "Teal",
    "White": "White",
    "Yellow": "Yellow",
    "Dark Blue": "Navy Blue",
    "Dark Green": "Mehendi",
    "Light Blue": "Aqua Blue",
    "Light Green": "Mehendi",
    "Magenta": "Pink",
}

SNAPDEAL_COLOR_MAPPING = {
    "Aqua Blue": "Aqua Blue",
    "Beige": "Beige",
    "Black": "Black",
    "Blue": "Blue",
    "Brown": "Brown",
    "Coral": "Coral",
    "Cream": "Cream",
    "Gold": "Gold",
    "Green": "Green",
    "Grey": "Grey",
    "Grey Melange": "Grey Melange",
    "Khaki": "Khaki",
    "Lavender": "Lavender",
    "Maroon": "Maroon",
    "Multicolor": "Multicolor",
    "Mustard": "Mustard",
    "Navy Blue": "Navy Blue",
    "Nude": "Nude",
    "Olive": "Olive",
    "Orange": "Orange",
    "Peach": "Peach",
    "Pink": "Pink",
    "Purple": "Purple",
    "Red": "Red",
    "Rust": "Rust",
    "Silver": "Silver",
    "Teal": "Teal",
    "White": "White",
    "Yellow": "Yellow",

    # Meesho values not available exactly in Snapdeal
    "Dark Blue": "Navy Blue",
    "Dark Green": "Green",
    "Mehendi": "Olive",
    "Metallic": "Silver",

    # Additional Snapdeal supported normalization
    "Burgundy": "Maroon",
    "Wine": "Wine",
    "Coffee": "Coffee",
    "Coffee Brown": "Coffee Brown",
    "Charcoal": "Charcoal",
    "Mauve": "Mauve",
    "Mint Green": "Mint Green",
    "Sea Green": "Sea Green",
    "Sky Blue": "Sky Blue",
    "Fuchsia": "Fuchsia",
    "Rama": "Rama",
    "Rani": "Rani",
    "Rose Gold": "Rose Gold",
    "Off White": "Off White",
    "Indigo": "Indigo",
    "Lime Green": "Lime Green",
}

SNAPDEAL_SET_CONTENTS_MAPPING = {
    "running_blouse": "With Unstitched Blouse Piece",
    "saree_with_multiple_blouse": "With Unstitched Blouse Piece",
    "semi_stitched_blouse": "With Unstitched Blouse Piece",
    "separate_blouse_piece": "With Unstitched Blouse Piece",

    "stitched_blouse": "With Stitched Blouse",

    "without_blouse": "Without Blouse Piece",
}