MYNTRA_ALLOWED_BLOUSE_FABRIC = {
    "Art Silk",
    "Pure Silk",
    "Pure Cotton",
    "Poly Georgette",
    "Poly Crepe",
    "Poly Chiffon",
    "Jute Silk",
    "Tissue",
    "Velvet",
    "Viscose Rayon",
    "Net",
    "Jute Cotton",
    "Polycotton",
    "Voile",
    "Organza",
    "Pure Georgette",
    "Pure Crepe",
    "Pure Chiffon",
    "Supernet",
    "Satin",
    "Silk Cotton",
    "Cotton Blend",
    "NA",
    "Silk Blend",
    "Poly Silk",
    "Polyester",
    "Brocade",
    "Brasso",
    "Lace",
    "Pure Linen",
    "Linen Blend",
    "Liva",
    "Lycra",
    "Modal Silk",
    "Viscose Georgette",
    "Bemberg Crepe",
}
