MYNTRA_ALLOWED_COLORS = {
    "Red",
    "Blue",
    "Green",
    "Black",
    "Purple",
    "White",
    "Pink",
    "Grey",
    "Brown",
    "Yellow",
    "Orange",
    "Navy Blue",
    "Maroon",
    "Cream",
    "Silver",
    "Gold",
    "Tan",
    "Beige",
    "Peach",
    "Multi",
    "Copper",
    "Steel",
    "Olive",
    "Khaki",
    "Rose",
    "Taupe",
    "Off White",
    "Metallic",
    "Charcoal",
    "Grey Melange",
    "Turquoise Blue",
    "Coffee Brown",
    "Sea Green",
    "Lavender",
    "Lime Green",
    "Magenta",
    "Burgundy",
    "Teal",
    "Nude",
    "Bronze",
    "Fluorescent Green",
    "Rust",
    "Mustard",
    "NA",
    "Mauve",
    "Coral",
    "Rose Gold",
    "Assorted",
    "Champagne",
    "Fuchsia",
    "Violet",
    "Camel Brown",
    "Transparent",
}
