MYNTRA_ALLOWED_ORNAMENTATION = {
    "Embroidered",
    "Zardozi",
    "Sequinned",
    "Mirror Work",
    "Beads and Stones",
    "Mukaish",
    "Patchwork",
    "NA",
    "Jaali",
    "Kashida",
    "Phulkari",
    "Kutchi Embroidery",
    "Aari Work",
    "Schiffli",
    "Zari",
    "Chikankari",
    "Gotta Patti",
}
