MYNTRA_ALLOWED_PRINT_OR_PATTERN_TYPE = {
    "Floral",
    "Paisley",
    "Abstract",
    "Polka Dots",
    "Geometric",
    "Woven Design",
    "Bandhani",
    "Leheriya",
    "Solid",
    "Ethnic Motifs",
    "Tie and Dye",
    "Embellished",
    "Checked",
    "Striped",
    "Colourblocked",
    "Ombre",
    "Bagh",
    "Dabu",
    "Ajrak",
    "Kalamkari",
    "Warli",
    "Batik",
}
