MYNTRA_ALLOWED_SAREE_FABRIC = {
    "Art Silk",
    "Pure Silk",
    "Pure Cotton",
    "Poly Georgette",
    "Poly Crepe",
    "Poly Chiffon",
    "Jute Silk",
    "Tissue",
    "Velvet",
    "Viscose Rayon",
    "Net",
    "Jute Cotton",
    "Polycotton",
    "Voile",
    "Organza",
    "Pure Georgette",
    "Pure Crepe",
    "Pure Chiffon",
    "Supernet",
    "Satin",
    "Silk Cotton",
    "Cotton Blend",
    "Silk Blend",
    "Poly Silk",
    "Pure Linen",
    "Linen Blend",
    "Polyester",
    "Nylon",
    "Brocade",
    "Brasso",
    "Lace",
    "Khandua Silk",
    "Pashmina",
    "Liva",
    "Lycra",
    "Lame",
    "Modal Silk",
    "Bemberg Crepe",
    "Viscose Georgette",
    "Silk Chiffon",
    "Silk Georgette Satin",
    "Silk Crepe",
}
