MYNTRA_ALLOWED_TECHNIQUE = {
    "Bagh",
    "Baluchari",
    "Banarasi",
    "Bandhani",
    "Bhagalpuri",
    "Chanderi",
    "Ikat",
    "Jamdani",
    "Kanjeevaram",
    "Kasavu",
    "Kota",
    "Leheriya",
    "Maheshwari",
    "Mangalagiri",
    "Mysore Silk",
    "Narayan Peth",
    "Patola",
    "Pochampally",
    "Sambalpuri",
    "Taant",
    "Tussar",
    "Venkatgiri",
    "Khadi",
    "NA",
    "Dharmavaram",
    "Kovai",
    "Chettinad",
    "Muga",
    "Uppada",
    "Garad",
    "Paithani",
    "Arani",
    "Dabu",
    "Bagru",
    "Sungudi",
    "Murshidabad silk",
    "Bomkai silk",
    "Ilkal",
    "Gadwal",
    "Block Print",
    "Laal Paar",
}
