MYNTRA_REQUIRED_COLORS = {
    "Red": "Red",
    "Blue": "Blue",
    "Green": "Green",
    "Black": "Black",
    "Purple": "Purple",
    "White": "White",
    "Pink": "Pink",
    "Grey": "Grey",
    "Brown": "Brown",
    "Yellow": "Yellow",
    "Orange": "Orange",
    "Navy Blue": "Navy Blue",
    "Maroon": "Maroon",
    "Cream": "Cream",
    "Silver": "Silver",
    "Gold": "Gold",
    "Tan": "Tan",
    "Beige": "Beige",
    "Peach": "Peach",
    "Multi": "Multi",
    "Copper": "Copper",
    "Steel": "Steel",
    "Olive": "Olive",
    "Khaki": "Khaki",
    "Rose": "Rose",
    "Taupe": "Taupe",
    "Off White": "Off White",
    "Metallic": "Metallic",
    "Charcoal": "Charcoal",
    "Grey Melange": "Grey Melange",
    "Turquoise Blue": "Turquoise Blue",
    "Coffee Brown": "Coffee Brown",
    "Sea Green": "Sea Green",
    "Lavender": "Lavender",
    "Lime Green": "Lime Green",
    "Magenta": "Magenta",
    "Burgundy": "Burgundy",
    "Teal": "Teal",
    "Nude": "Nude",
    "Bronze": "Bronze",
    "Fluorescent Green": "Fluorescent Green",
    "Rust": "Rust",
    "Mustard": "Mustard",
    "NA": "NA",
    "Mauve": "Mauve",
    "Coral": "Coral",
    "Rose Gold": "Rose Gold",
    "Assorted": "Assorted",
    "Champagne": "Champagne",
    "Fuchsia": "Fuchsia",
    "Violet": "Violet",
    "Camel Brown": "Camel Brown",
    "Transparent": "Transparent",
}


MYNTRA_RULES = {
    "color": {
        "label": "Color",
        "required": True,
        "mapping": MYNTRA_REQUIRED_COLORS,
    },
}