# Generated by Django 6.0.7 on 2026-08-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_state_profile_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='accounts.profile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
