# Generated by Django 6.0.7 on 2026-08-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uservendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVendor',
        ),
    ]
