# Generated by Django 4.2.30 on 2026-06-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_no', models.CharField(blank=True, max_length=4, null=True)),
                ('style_description', models.CharField(blank=True, max_length=500, null=True)),
                ('style_id', models.CharField(blank=True, max_length=8, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=40, null=True)),
                ('hsn', models.CharField(blank=True, max_length=8, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('van', models.CharField(blank=True, max_length=20, null=True)),
                ('sku', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('old_sku', models.CharField(blank=True, max_length=30, null=True)),
                ('ean', models.CharField(blank=True, max_length=20, null=True)),
                ('product_image_link', models.URLField(blank=True, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcode_image/')),
                ('live_status', models.BooleanField(default=False)),
                ('image_urls', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article_type')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size')),
            ],
        ),
    ]
