# Generated by Django 4.2.30 on 2026-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sku_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='pattern',
            field=models.CharField(blank=True, choices=[('APPLIQUE', 'Applique'), ('CHECKED', 'Checked'), ('CHIKANKARI', 'Chikankari'), ('COLORBLOCKED', 'Colorblocked'), ('DIGITAL_PRINT', 'Digital Print'), ('DYED_WASHED', 'Dyed/ Washed'), ('EMBELLISHED', 'Embellished'), ('EMBROIDERED', 'Embroidered'), ('PRINTED', 'Printed'), ('SELF_DESIGN', 'Self-Design'), ('SOLID', 'Solid'), ('STRIPED', 'Striped'), ('WOVEN_DESIGN', 'Woven Design'), ('ZARI_EMBROIDERED', 'Zari Embroidered'), ('ZARI_WOVEN', 'Zari Woven')], max_length=50, null=True),
        ),
    ]
