# Generated by Django 4.2.30 on 2026-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sku_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='pallu_details',
            field=models.CharField(blank=True, choices=[('colourblock', 'Colourblock'), ('embellished', 'Embellished'), ('embroidered', 'Embroidered'), ('half_half', 'Half & Half'), ('jacquard', 'Jacquard'), ('printed', 'Printed'), ('same_as_border', 'Same as Border'), ('same_as_saree', 'Same as Saree'), ('solid', 'Solid'), ('woven_design', 'Woven Design'), ('zari_woven', 'Zari Woven')], max_length=50, null=True),
        ),
    ]
