# Generated by Django 4.2.30 on 2026-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sku_pallu_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='blouse',
            field=models.CharField(blank=True, choices=[('running_blouse', 'Running Blouse'), ('saree_with_multiple_blouse', 'Saree with Multiple Blouse'), ('semi_stitched_blouse', 'Semi-Stitched Blouse'), ('separate_blouse_piece', 'Separate Blouse Piece'), ('stitched_blouse', 'Stitched Blouse'), ('without_blouse', 'Without Blouse')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='blouse_color',
            field=models.CharField(blank=True, choices=[('aqua_blue', 'Aqua Blue'), ('beige', 'Beige'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('coral', 'Coral'), ('cream', 'Cream'), ('gold', 'Gold'), ('green', 'Green'), ('grey', 'Grey'), ('grey_melange', 'Grey Melange'), ('khaki', 'Khaki'), ('lavender', 'Lavender'), ('maroon', 'Maroon'), ('mehendi', 'Mehendi'), ('metallic', 'Metallic'), ('multicolor', 'Multicolor'), ('mustard', 'Mustard'), ('navy_blue', 'Navy Blue'), ('nude', 'Nude'), ('olive', 'Olive'), ('orange', 'Orange'), ('peach', 'Peach'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('rust', 'Rust'), ('silver', 'Silver'), ('teal', 'Teal'), ('white', 'White'), ('yellow', 'Yellow')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='blouse_fabric',
            field=models.CharField(blank=True, choices=[('acrylic', 'Acrylic'), ('art_silk', 'Art Silk'), ('bamboo', 'Bamboo'), ('banarasi_silk', 'Banarasi Silk'), ('bangalori_silk', 'Bangalori Silk'), ('brocade', 'Brocade'), ('chambray', 'Chambray'), ('chanderi_cotton', 'Chanderi Cotton'), ('chanderi_silk', 'Chanderi Silk'), ('chiffon', 'Chiffon'), ('cotton', 'Cotton'), ('cotton_blend', 'Cotton Blend'), ('cotton_cambric', 'Cotton Cambric'), ('cotton_linen', 'Cotton Linen'), ('cotton_silk', 'Cotton Silk'), ('cotton_slub', 'Cotton Slub'), ('crepe', 'Crepe'), ('denim', 'Denim'), ('dola_silk', 'Dola Silk'), ('dupion_silk', 'Dupion Silk'), ('eri_silk', 'Eri Silk'), ('georgette', 'Georgette'), ('italian_silk', 'Italian Silk'), ('jacquard', 'Jacquard'), ('jute_cotton', 'Jute Cotton'), ('jute_khadi', 'Jute Khadi'), ('jute_silk', 'Jute Silk'), ('kanjeevaram_silk', 'Kanjeevaram Silk'), ('khadi_cotton', 'Khadi Cotton'), ('khadi_silk', 'Khadi Silk'), ('khan', 'Khan'), ('kora_muslin', 'Kora Muslin'), ('kota_doria_cotton', 'Kota Doria Cotton'), ('kota_doria_silk', 'Kota Doria Silk'), ('lace', 'Lace'), ('linen', 'Linen'), ('linen_blend', 'Linen Blend'), ('litchi_silk', 'Litchi Silk'), ('lycra', 'Lycra'), ('lycra_blend', 'Lycra Blend'), ('malai_silk', 'Malai Silk'), ('muga_silk', 'Muga Silk'), ('mulberry_silk', 'Mulberry Silk'), ('mulmul', 'Mulmul'), ('muslin', 'Muslin'), ('mysore_silk', 'Mysore Silk'), ('net', 'Net'), ('no_blouse', 'No Blouse'), ('nylon', 'Nylon'), ('organza', 'Organza'), ('paper_silk', 'Paper Silk'), ('pashmina', 'Pashmina'), ('poly_blend', 'Poly Blend'), ('poly_chiffon', 'Poly Chiffon'), ('poly_crepe', 'Poly Crepe'), ('poly_georgette', 'Poly Georgette'), ('poly_silk', 'Poly Silk'), ('polycotton', 'Polycotton'), ('polyester', 'Polyester'), ('rayon', 'Rayon'), ('rayon_slub', 'Rayon Slub'), ('sana_silk', 'Sana Silk'), ('satin', 'Satin'), ('satin_silk', 'Satin Silk'), ('shantoon', 'Shantoon'), ('silk', 'Silk'), ('silk_blend', 'Silk Blend'), ('soft_silk', 'Soft Silk'), ('super_net', 'Super Net'), ('suti', 'Suti'), ('synthetic', 'Synthetic'), ('synthetic_crepe', 'Synthetic Crepe'), ('taant', 'Taant'), ('taffeta_silk', 'Taffeta Silk'), ('tissue', 'Tissue'), ('tussar', 'Tussar'), ('tussar_silk', 'Tussar Silk'), ('twill_net', 'Twill Net'), ('velvet', 'Velvet'), ('vichitra_silk', 'Vichitra Silk'), ('viscose', 'Viscose'), ('viscose_rayon', 'Viscose Rayon'), ('viscose_silk', 'Viscose Silk'), ('voile', 'Voile'), ('wool', 'Wool')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='blouse_length',
            field=models.CharField(blank=True, choices=[('0.8', '0.8'), ('0.9', '0.9'), ('1', '1'), ('1.1', '1.1'), ('1.2', '1.2')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='blouse_pattern',
            field=models.CharField(blank=True, choices=[('embellished', 'Embellished'), ('embroidered', 'Embroidered'), ('foil_printed', 'Foil Printed'), ('jacquard', 'Jacquard'), ('printed', 'Printed'), ('same_as_border', 'Same as Border'), ('same_as_pallu', 'Same as Pallu'), ('same_as_saree', 'Same as Saree'), ('sequence', 'Sequence'), ('sequinned', 'Sequinned'), ('solid', 'Solid'), ('woven_design', 'Woven Design'), ('zari_woven', 'Zari Woven')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='border',
            field=models.CharField(blank=True, choices=[('embellished', 'Embellished'), ('embroidered', 'Embroidered'), ('lace', 'Lace'), ('no_border', 'No Border'), ('printed', 'Printed'), ('solid', 'Solid'), ('temple_border', 'Temple Border'), ('woven_design', 'Woven Design'), ('zari', 'Zari')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='border_width',
            field=models.CharField(blank=True, choices=[('big_border', 'Big Border'), ('no', 'No'), ('no_border', 'No Border'), ('small_border', 'Small Border')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='loom_type',
            field=models.CharField(blank=True, choices=[('handloom', 'Handloom'), ('powerloom', 'Powerloom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='occation',
            field=models.CharField(blank=True, choices=[('bridal_saree', 'Bridal Saree'), ('celebrity_inspired', 'Celebrity Inspired'), ('daily', 'Daily'), ('farewell', 'Farewell'), ('party', 'Party'), ('traditional', 'Traditional'), ('wedding', 'Wedding')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='ornamentation',
            field=models.CharField(blank=True, choices=[('aari_work', 'Aari Work'), ('applique', 'Applique'), ('beads_stones', 'Beads & Stones'), ('brocade', 'Brocade'), ('brooch', 'Brooch'), ('cutwork', 'Cutwork'), ('embroidered', 'Embroidered'), ('frills', 'Frills'), ('gota_work', 'Gota Work'), ('jacquard', 'Jacquard'), ('kundan', 'Kundan'), ('lace_border', 'Lace Border'), ('maggam_work', 'Maggam Work'), ('mirror_work', 'Mirror Work'), ('mukaish', 'Mukaish'), ('not_applicable', 'Not Applicable'), ('patchwork', 'Patchwork'), ('pintucks', 'Pintucks'), ('pom_pom', 'Pom-Pom'), ('ruffle', 'Ruffle'), ('sequinned', 'Sequinned'), ('tassels_latkans', 'Tassels and Latkans'), ('zardozi', 'Zardozi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='print_or_pattern_type',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('ajrakh', 'Ajrakh'), ('animal', 'Animal'), ('applique', 'Applique'), ('aztec', 'Aztec'), ('bagru_print', 'Bagru Print'), ('bandhani', 'Bandhani'), ('batik', 'Batik'), ('block', 'Block'), ('bohemian', 'Bohemian'), ('boho_saree', 'Boho Saree'), ('botanical', 'Botanical'), ('butterfly', 'Butterfly'), ('checked', 'Checked'), ('chevron', 'Chevron'), ('colorblocked', 'Colorblocked'), ('elephant', 'Elephant'), ('embellished', 'Embellished'), ('ethnic_motif', 'Ethnic Motif'), ('floral', 'Floral'), ('foil', 'Foil'), ('geometric', 'Geometric'), ('gradient', 'Gradient'), ('graphic', 'Graphic'), ('hand_painted', 'Hand Painted'), ('herringbone', 'Herringbone'), ('houndstooth', 'Houndstooth'), ('ikat', 'Ikat'), ('kalamkari', 'Kalamkari'), ('leheriya', 'Leheriya'), ('leopard', 'Leopard'), ('madhubani', 'Madhubani'), ('micro', 'Micro'), ('moti_work', 'Moti Work'), ('nath', 'Nath'), ('newspaper_print', 'Newspaper Print'), ('paisley', 'Paisley'), ('peacock', 'Peacock'), ('phulkari', 'Phulkari'), ('polka_dot', 'Polka Dot'), ('quirky', 'Quirky'), ('ribbon', 'Ribbon'), ('scenic', 'Scenic'), ('shibori', 'Shibori'), ('solid', 'Solid'), ('stripe', 'Stripe'), ('tie_and_dye', 'Tie and Dye'), ('tiger', 'Tiger'), ('tribal', 'Tribal'), ('warli', 'Warli'), ('woven_design', 'Woven Design'), ('zari_woven', 'Zari Woven'), ('zari_butta', 'Zari Butta'), ('zebra', 'Zebra')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='saree_fabric',
            field=models.CharField(blank=True, choices=[('acrylic', 'Acrylic'), ('art_silk', 'Art Silk'), ('aura_silk', 'Aura Silk'), ('bamboo', 'Bamboo'), ('banarasi_silk', 'Banarasi Silk'), ('binny_silk', 'Binny Silk'), ('brocade', 'Brocade'), ('chambray', 'Chambray'), ('chanderi_cotton', 'Chanderi Cotton'), ('chanderi_silk', 'Chanderi Silk'), ('chiffon', 'Chiffon'), ('chinnon', 'Chinnon'), ('cotton', 'Cotton'), ('cotton_blend', 'Cotton Blend'), ('cotton_cambric', 'Cotton Cambric'), ('cotton_linen', 'Cotton Linen'), ('cotton_silk', 'Cotton Silk'), ('cotton_slub', 'Cotton Slub'), ('crepe', 'Crepe'), ('denim', 'Denim'), ('dola_silk', 'Dola Silk'), ('dupion_silk', 'Dupion Silk'), ('eri_silk', 'Eri Silk'), ('georgette', 'Georgette'), ('italian_silk', 'Italian Silk'), ('jacquard', 'Jacquard'), ('jimmy_choo', 'Jimmy Choo'), ('jute_cotton', 'Jute Cotton'), ('jute_khadi', 'Jute Khadi'), ('jute_silk', 'Jute Silk'), ('kanchi_silk', 'Kanchi Silk'), ('kanjeevaram_silk', 'Kanjeevaram Silk'), ('khadi_cotton', 'Khadi Cotton'), ('khadi_silk', 'Khadi Silk'), ('khan', 'Khan'), ('kora_muslin', 'Kora Muslin'), ('kota_doria_cotton', 'Kota Doria Cotton'), ('kota_doria_silk', 'Kota Doria Silk'), ('lace', 'Lace'), ('linen', 'Linen'), ('linen_blend', 'Linen Blend'), ('litchi_silk', 'Litchi Silk'), ('lycra', 'Lycra'), ('lycra_blend', 'Lycra Blend'), ('malai_cotton', 'Malai Cotton'), ('malai_silk', 'Malai Silk'), ('muga_silk', 'Muga Silk'), ('mulberry_silk', 'Mulberry Silk'), ('mulmul', 'Mulmul'), ('murshidabad_silk', 'Murshidabad Silk'), ('muslin', 'Muslin'), ('mysore_silk', 'Mysore Silk'), ('net', 'Net'), ('net_soft_net', 'Net (Soft Net)'), ('net_supernet', 'Net (Supernet)'), ('nylon', 'Nylon'), ('organza', 'Organza'), ('paper_silk', 'Paper Silk'), ('pashmina', 'Pashmina'), ('poly_blend', 'Poly Blend'), ('poly_chiffon', 'Poly Chiffon'), ('poly_crepe', 'Poly Crepe'), ('poly_georgette', 'Poly Georgette'), ('poly_silk', 'Poly Silk'), ('polycotton', 'Polycotton'), ('polyester', 'Polyester'), ('rayon', 'Rayon'), ('rayon_slub', 'Rayon Slub'), ('sana_silk', 'Sana Silk'), ('satin', 'Satin'), ('satin_silk', 'Satin Silk'), ('shantoon', 'Shantoon'), ('silk', 'Silk'), ('silk_blend', 'Silk Blend'), ('simmer', 'Simmer'), ('soft_silk', 'Soft Silk'), ('super_net', 'Super Net'), ('suti', 'Suti'), ('synthetic', 'Synthetic'), ('synthetic_crepe', 'Synthetic Crepe'), ('taant', 'Taant'), ('taffeta_silk', 'Taffeta Silk'), ('tanchoi_silk', 'Tanchoi Silk'), ('tissue', 'Tissue'), ('tripura_silk', 'Tripura Silk'), ('tussar', 'Tussar'), ('tussar_silk', 'Tussar Silk'), ('twill_net', 'Twill Net'), ('vayal', 'Vayal'), ('velvet', 'Velvet'), ('vichitra_silk', 'Vichitra Silk'), ('viscose', 'Viscose'), ('viscose_rayon', 'Viscose Rayon'), ('viscose_silk', 'Viscose Silk'), ('voile', 'Voile'), ('wool', 'Wool'), ('zamato', 'Zamato')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='saree_length',
            field=models.CharField(blank=True, choices=[('5', '5'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.6', '5.6'), ('5.7', '5.7'), ('5.8', '5.8'), ('5.9', '5.9'), ('6', '6'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('8', '8'), ('8.8', '8.8'), ('9', '9'), ('9.6', '9.6')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='transparency',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='type',
            field=models.CharField(blank=True, choices=[('assam_silk', 'Assam Silk'), ('bagh', 'Bagh'), ('balaton_silk', 'Balaton Silk'), ('baluchari', 'Baluchari'), ('banarasi', 'Banarasi'), ('bandhani', 'Bandhani'), ('bangalori_silk', 'Bangalori Silk'), ('begumpuri', 'Begumpuri'), ('belt_saree', 'Belt Saree'), ('bhagalpuri', 'Bhagalpuri'), ('bishnupuri', 'Bishnupuri'), ('bollywood', 'Bollywood'), ('bomkai_sonepuri', 'Bomkai/Sonepuri'), ('brasso', 'Brasso'), ('cape_saree', 'Cape Saree'), ('chanderi', 'Chanderi'), ('chettinad', 'Chettinad'), ('chikankari', 'Chikankari'), ('christian_bride', 'Christian Bride'), ('cowdial_sarees', 'Cowdial Sarees'), ('crush', 'Crush'), ('darbari', 'Darbari'), ('dhavani', 'Dhavani'), ('dhoti_saree', 'Dhoti Saree'), ('durga_puja_saree', 'Durga Puja Saree'), ('gadhwal', 'Gadhwal'), ('gadwal', 'Gadwal'), ('garad', 'Garad'), ('gharchola', 'Gharchola'), ('hakoba', 'Hakoba'), ('half_and_half', 'Half and half'), ('hazar_buti', 'Hazar Buti'), ('holographic_saree', 'Holographic Saree'), ('ikat', 'Ikat'), ('ilkal', 'Ilkal'), ('irkal', 'Irkal'), ('irkal_ilkal', 'Irkal / Ilkal'), ('jacket_koti_saree', 'Jacket/Koti Saree'), ('kaantha', 'Kaantha'), ('kanjeevaram', 'Kanjeevaram'), ('kasavu', 'Kasavu'), ('kasavu_kerala_saree', 'Kasavu (Kerala Saree)'), ('kashmiri', 'Kashmiri'), ('katan', 'Katan'), ('kathpadar', 'Kathpadar'), ('khadi', 'Khadi'), ('khan', 'Khan'), ('khasi_jainsem_saree', 'Khasi Jainsem Saree'), ('konrad_mubbhagam', 'Konrad And Mubbhagam'), ('kota', 'Kota'), ('kotki', 'Kotki'), ('langa_voni', 'Langa Voni'), ('lehenga_saree', 'Lehenga Saree'), ('leheriya', 'Leheriya'), ('maheshwari', 'Maheshwari'), ('maheshwari_silk', 'Maheshwari Silk'), ('mangalagiri', 'Mangalagiri'), ('manipuri', 'Manipuri'), ('marble', 'Marble'), ('matka', 'Matka'), ('mekhela_chador', 'Mekhela chador'), ('metallic', 'Metallic'), ('monochrome', 'Monochrome'), ('muga_silk', 'Muga Silk'), ('muggu', 'Muggu'), ('mysore_silk', 'Mysore Silk'), ('narayan_peth', 'Narayan Peth'), ('nauvari', 'Nauvari'), ('no_type', 'No Type'), ('paithani', 'Paithani'), ('palazzo_saree', 'Palazzo Saree'), ('panetar', 'Panetar'), ('pasapalli', 'Pasapalli'), ('patola', 'Patola'), ('pochampally', 'Pochampally'), ('ready_to_wear', 'Ready to Wear'), ('ruffle_saree', 'Ruffle Saree'), ('sambhalpuri', 'Sambhalpuri'), ('sana_silk', 'Sana Silk'), ('shaded', 'Shaded'), ('shimmer', 'Shimmer'), ('sungudi', 'Sungudi'), ('swastik', 'Swastik'), ('taant', 'Taant'), ('tangail', 'Tangail'), ('tripura_silk', 'Tripura Silk'), ('tussar', 'Tussar'), ('two_tone', 'Two-Tone'), ('upada_pattu', 'Upada Pattu'), ('venkatgiri', 'Venkatgiri'), ('jamdani', 'Jamdani')], max_length=50, null=True),
        ),
    ]
