# Generated by Django 4.2.30 on 2026-06-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sku_blouse_sku_blouse_color_sku_blouse_fabric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='occation',
            new_name='occasion',
        ),
    ]
