# Generated by Django 4.2.30 on 2026-06-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_occation_sku_occasion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='product_image_link',
            new_name='product_image_link_1',
        ),
        migrations.AddField(
            model_name='sku',
            name='product_image_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='product_image_link_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='product_image_link_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='product_image_link_5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
