# Generated by Django 4.2.30 on 2026-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_product_image_link_sku_product_image_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='blouse_color',
            field=models.CharField(blank=True, choices=[('aqua_blue', 'Aqua Blue'), ('beige', 'Beige'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('coral', 'Coral'), ('cream', 'Cream'), ('gold', 'Gold'), ('green', 'Green'), ('grey', 'Grey'), ('grey_melange', 'Grey Melange'), ('khaki', 'Khaki'), ('lavender', 'Lavender'), ('maroon', 'Maroon'), ('mehendi', 'Mehendi'), ('metallic', 'Metallic'), ('multicolor', 'Multicolor'), ('mustard', 'Mustard'), ('navy_blue', 'Navy Blue'), ('nude', 'Nude'), ('olive', 'Olive'), ('orange', 'Orange'), ('peach', 'Peach'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('rust', 'Rust'), ('silver', 'Silver'), ('teal', 'Teal'), ('white', 'White'), ('yellow', 'Yellow'), ('dark_blue', 'Dark Blue'), ('dark_green', 'Dark Green'), ('light_blue', 'Light Blue'), ('light_green', 'Light Green'), ('magenta', 'Magenta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='occasion',
            field=models.CharField(blank=True, choices=[('bridal_saree', 'Bridal Saree'), ('celebrity_inspired', 'Celebrity Inspired'), ('daily', 'Daily'), ('farewell', 'Farewell'), ('party', 'Party'), ('traditional', 'Traditional'), ('wedding', 'Wedding'), ('party_and_festive', 'Party & Festive')], max_length=50, null=True),
        ),
    ]
