# Generated by Django 4.2.30 on 2026-07-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sku_blouse_color_alter_sku_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('video_type', models.CharField(choices=[('forward', 'Forward'), ('return', 'Return')], default='forward', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
