# Generated by Django 4.2.30 on 2026-07-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_state_profile_pin'),
        ('main', '0010_vms'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.article_type'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.brand'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.color'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.gender'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.size'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
    ]
