# Generated by Django 4.2.30 on 2026-07-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_state_profile_pin'),
        ('main', '0011_brand_vendor_alter_sku_article_type_alter_sku_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
    ]
