# Generated by Django 4.2.30 on 2026-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_vms_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('MEESHO', 'Meesho'), ('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon'), ('MYNTRA', 'Myntra'), ('SNAPDEAL', 'Snapdeal')], db_index=True, max_length=50)),
                ('attribute', models.CharField(choices=[('COLOR', 'Color'), ('TECHNIQUE', 'Technique'), ('OCCASION', 'Occasion'), ('SAREE_FABRIC', 'Saree Fabric'), ('BLOUSE_FABRIC', 'Blouse Fabric'), ('BLOUSE', 'Blouse'), ('PATTERN', 'Pattern'), ('PRINT_OR_PATTERN_TYPE', 'Print Or Pattern Type'), ('ORNAMENTATION', 'Ornamentation'), ('BORDER', 'Border')], db_index=True, max_length=100)),
                ('source_value', models.CharField(max_length=255)),
                ('mapped_value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['marketplace', 'attribute', 'source_value'], name='main_market_marketp_f2ef15_idx')],
                'unique_together': {('marketplace', 'attribute', 'source_value')},
            },
        ),
    ]
