# Generated by Django 6.0.7 on 2026-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_marketplacemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='key_words',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacemapping',
            name='attribute',
            field=models.CharField(choices=[('COLOR', 'Color'), ('TECHNIQUE', 'Technique'), ('OCCASION', 'Occasion'), ('SAREE_FABRIC', 'Saree Fabric'), ('BLOUSE_FABRIC', 'Blouse Fabric'), ('BLOUSE', 'Blouse'), ('PATTERN', 'Pattern'), ('PRINT_OR_PATTERN_TYPE', 'Print Or Pattern Type'), ('ORNAMENTATION', 'Ornamentation'), ('BORDER', 'Border'), ('BLOUSE_PATTERN', 'Blouse Pattern'), ('PALLU_DETAILS', 'Pallu Details'), ('BORDER_WIDTH', 'Border Width')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sku',
            name='print_or_pattern_type',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('ajrakh', 'Ajrakh'), ('animal', 'Animal'), ('applique', 'Applique'), ('aztec', 'Aztec'), ('bagru_print', 'Bagru Print'), ('bandhani', 'Bandhani'), ('batik', 'Batik'), ('block', 'Block'), ('bohemian', 'Bohemian'), ('boho_saree', 'Boho Saree'), ('botanical', 'Botanical'), ('butterfly', 'Butterfly'), ('checked', 'Checked'), ('chevron', 'Chevron'), ('colorblocked', 'Colorblocked'), ('elephant', 'Elephant'), ('embellished', 'Embellished'), ('ethnic_motif', 'Ethnic Motif'), ('floral', 'Floral'), ('foil', 'Foil'), ('geometric', 'Geometric'), ('gradient', 'Gradient'), ('graphic', 'Graphic'), ('hand_painted', 'Hand Painted'), ('herringbone', 'Herringbone'), ('houndstooth', 'Houndstooth'), ('ikat', 'Ikat'), ('kalamkari', 'Kalamkari'), ('leheriya', 'Leheriya'), ('leopard', 'Leopard'), ('madhubani', 'Madhubani'), ('micro', 'Micro'), ('moti_work', 'Moti Work'), ('nath', 'Nath'), ('newspaper_print', 'Newspaper Print'), ('paisley', 'Paisley'), ('peacock', 'Peacock'), ('phulkari', 'Phulkari'), ('polka_dot', 'Polka Dot'), ('quirky', 'Quirky'), ('ribbon', 'Ribbon'), ('scenic', 'Scenic'), ('shibori', 'Shibori'), ('solid', 'Solid'), ('stripe', 'Stripe'), ('tie_and_dye', 'Tie and Dye'), ('tiger', 'Tiger'), ('tribal', 'Tribal'), ('warli', 'Warli'), ('woven_design', 'Woven Design'), ('zari_woven', 'Zari Woven'), ('zari_butta', 'Zari butta'), ('zebra', 'Zebra')], max_length=50, null=True),
        ),
    ]
