# Generated by Django 6.0.7 on 2026-08-12 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_state_profile_pin'),
        ('main', '0014_sku_key_words_alter_marketplacemapping_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='accounts.profile'),
        ),
    ]
