# Generated by Django 6.0.7 on 2026-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_brand_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='snapdeal_brand_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
