# Generated by Django 6.0.7 on 2026-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_brand_snapdeal_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='product_image_link_6',
            field=models.URLField(blank=True, null=True),
        ),
    ]
