FLIPKART_ALLOWED_BLOUSE_FABRIC = {
    "Acrylic Wool",
    "Art Silk",
    "Banarasi Silk",
    "Brasso",
    "Brocade",
    "Cambric",
    "Cashmere",
    "Chanderi",
    "Chenille",
    "Chiffon",
    "Corduroy",
    "Cotton",
    "Cotton Linen Blend",
    "Cotton Lycra Blend",
    "Cotton Slub",
    "Crepe",
    "Damask",
    "Denim",
    "Dupion Silk",
    "Flannel",
    "Georgette",
    "Glass Tissue",
    "Hoisery",
    "Jacquard",
    "Jute",
    "Khadi",
    "Kota Cotton",
    "Lace",
    "Linen",
    "Lycra",
    "Merino Wool",
    "Mettalic Yarn",
    "Modal",
    "Muslin",
    "NA",
    "Net",
    "Nylon",
    "Nylon Wool Blend",
    "Organza",
    "PU",
    "Poly Silk",
    "Polycotton",
    "Polyester",
    "Printed Silk",
    "Pure Chiffon",
    "Pure Crepe",
    "Pure Georgette",
    "Pure Silk",
    "Raw Silk",
    "Rayon",
    "Satin",
    "Sequined Fabric",
    "Shantung",
    "Shimmer Fabric",
    "Silk",
    "Silk Cotton Blend",
    "Silk Linen Blend",
    "Silk Wool Blend",
    "Suede",
    "Swiss Dot",
    "Synthetic",
    "Synthetic Chiffon",
    "Synthetic Crepe",
    "Synthetic Fabric",
    "Synthetic Georgette",
    "Taffeta",
    "Tissue",
    "Tissue Silk",
    "Tulle",
    "Tussar Silk",
    "Tweed",
    "Velvet",
    "Viscose",
    "Voile",
    "Wool",
    "Worsted Wool",
}
