FLIPKART_ALLOWED_FABRIC_CARE = {
    "Change Folds Regularly",
    "Cold Water Wash Only",
    "Do Not Use Softener",
    "Do not Bleach",
    "Do not Dry Clean",
    "Do not Iron",
    "Do not Iron on Print/Embroidery/Embellishment",
    "Do not Tumble Dry",
    "Do not Wring",
    "Dry Clean Only",
    "Dry Clean for the first wash, thereafter Hand Wash",
    "Dry in Shade",
    "Hand Wash",
    "Iron on Low Heat",
    "Iron on Reverse Side",
    "Machine Wash as per tag",
    "Steam Iron only",
    "Use Mild Detergent Only",
    "Wash with Like Colors",
}
