FLIPKART_ALLOWED_ORNAMENTATION = {
    "Beads",
    "Brocade",
    "Cotton Thread",
    "Decorative Stones",
    "Floral Design",
    "Fringes",
    "Gota",
    "Kundan",
    "Lace",
    "Metal Embellishment",
    "Mirror",
    "Mukesh",
    "NA",
    "Patchwork",
    "Pom Pom",
    "Resham/ Silk Thread",
    "Ruffle",
    "Schiffli",
    "Sequinns",
    "Shimmer",
    "Silver Thread",
    "Swarovski Crystal",
    "Tassel",
    "Zari",
    "Zari Buta",
}
