FLIPKART_ALLOWED_PATTERN = {
    "Animal Print",
    "Applique",
    "Blocked Printed",
    "Checkered",
    "Color Block",
    "Digital Print",
    "Dyed",
    "Embellished",
    "Embroidered",
    "Floral Print",
    "Geometric Print",
    "Graphic Print",
    "Hand Painted",
    "Ombre",
    "Paisley",
    "Polka Print",
    "Printed",
    "Self Design",
    "Solid/Plain",
    "Striped",
    "Temple Border",
    "Tie-Dye",
    "Woven",
}
