FLIPKART_ALLOWED_PRINT_OR_PATTERN_TYPE = {
    "Abstract",
    "Ajrakh",
    "Animal Print",
    "Applique",
    "Aztec Print",
    "Bandhni",
    "Batik",
    "Block Print",
    "Botanical Prints",
    "Checkered",
    "Chevron/Zig Zag",
    "Colorblock",
    "Conversational",
    "Digital Prints",
    "Embellished",
    "Embroidered",
    "Ethnic Motifs",
    "Floral",
    "Foil Print",
    "Geometric",
    "Graphic",
    "Hand Paint",
    "Herringbone",
    "Human Figures",
    "Ikkat",
    "Kalamkari",
    "Leheriya",
    "Mirror work",
    "Ombre",
    "Paisley",
    "Polka",
    "Quirky",
    "Sanganeri",
    "Self Design",
    "Sequin",
    "Shibori",
    "Solid",
    "Striped",
    "Temple Border Prints",
    "Tie & Dye",
    "Tribal",
    "Typography",
    "Warli",
    "Woven Design",
}
