FLIPKART_ALLOWED_SAREE_FABRIC = {
    "Art Silk",
    "Brasso",
    "Brocade",
    "Chanderi",
    "Chiffon",
    "Cotton Blend",
    "Cotton Jute",
    "Cotton Linen",
    "Cotton Silk",
    "Crepe",
    "Dupion Silk",
    "Georgette",
    "Jacquard",
    "Jimmy Jimmy",
    "Jute Silk",
    "Khadi",
    "Lace",
    "Linen",
    "Lycra",
    "Lycra Blend",
    "Mulmul",
    "Muslin",
    "Net",
    "Nylon",
    "Organza",
    "Polyester",
    "Pure Cotton",
    "Pure Silk",
    "Raw Silk",
    "Satin",
    "Semi-Pashmina",
    "Silk Blend",
    "Supernet",
    "Tissue",
    "Tussar Silk",
    "Velvet",
    "Viscose Rayon",
}
