FLIPKART_ALLOWED_TECHNIQUE = {
    "Arani Pattu",
    "Assam Silk",
    "Baluchari",
    "Banarasi",
    "Bandhani",
    "Berhampuri",
    "Bhagalpuri",
    "Bollywood",
    "Chanderi",
    "Chettinadu",
    "Chinnalapattu",
    "Daily Wear",
    "Dharmavaram",
    "Dokhona",
    "Gadwal",
    "Garad",
    "Garara Saree",
    "Hand Batik",
    "Handloom",
    "Ikkat",
    "Ilkal",
    "JAINSEM KHASI DHARA",
    "JAINTIA DHARA TOH HYNDAI",
    "Jamdani",
    "KHASI DHARA CONTRAST",
    "KHASI DHARA MUKHLI",
    "Kalamkari",
    "Kanjivaram",
    "Kantha",
    "Kasavu",
    "Konrad",
    "Kota Doria",
    "Kovai",
    "Leheria",
    "Lucknow Chikankari",
    "Madhubani",
    "Madurai",
    "Maheshwari",
    "Mangalagiri",
    "Manipuri",
    "Mekhela Chador",
    "Mundum Neriyathum",
    "Murshidabad",
    "Mysore",
    "Narayanpet",
    "Paithani",
    "Palazzo Saree",
    "Pant Saree",
    "Patola",
    "Pochampally",
    "Pre Draped Saree",
    "Sambalpuri",
    "Saree with Attached Blouse",
    "Sharara Saree",
    "Tant",
    "Venkatagiri",
}
