MYSMME_ALLOWED_BLOUSE_FABRIC = {
    "Acrylic",
    "Art Silk",
    "Aura Silk",
    "Balaton Silk",
    "Bamboo",
    "Banarasi Silk",
    "Bangalori Silk",
    "Bhagalpuri",
    "Binny Silk",
    "Brasso",
    "Brocade",
    "Chambray",
    "Chanderi",
    "Chanderi Cotton",
    "Chanderi Silk",
    "Chiffon",
    "Chinnon",
    "Cotton",
    "Cotton Blend",
    "Cotton Cambric",
    "Cotton Linen",
    "Cotton Silk",
    "Cotton Slub",
    "Crepe",
    "Crush",
    "Denim",
    "Dola Silk",
    "Dupion Silk",
    "Eri Silk",
    "Georgette",
    "Hakoba",
    "Italian Silk",
    "Jacquard",
    "Jimmy Choo",
    "Jute Cotton",
    "Jute Khadi",
    "Jute Silk",
    "Kanchi Silk",
    "Kanjeevaram Silk",
    "Khadi",
    "Khadi Cotton",
    "Khadi Silk",
    "Kora Muslin",
    "Kota",
    "Kota Doria Cotton",
    "Kota Doria Silk",
    "Lace",
    "Linen",
    "Linen Blend",
    "Litchi Silk",
    "Lycra",
    "Lycra Blend",
    "Maheshwari Silk",
    "Malai Cotton",
    "Malai Silk",
    "Marble",
    "Matka",
    "Metallic",
    "Muga Silk",
    "Mulberry Silk",
    "Mulmul",
    "Murshidabad Silk",
    "Muslin",
    "Mysore Silk",
    "Net",
    "Nylon",
    "Organza",
    "Paper Silk",
    "Pashmina",
    "Poly Blend",
    "Poly Chiffon",
    "Poly Cotton",
    "Poly Crepe",
    "Poly Georgette",
    "Poly Silk",
    "Polyester",
    "Rayon Slub",
    "Sana Silk",
    "Satin",
    "Satin Silk",
    "Shantoon",
    "Shimmer",
    "Silk",
    "Silk Blend",
    "Soft Silk",
    "Super Net",
    "Suti",
    "Synthetic",
    "Taffeta Silk",
    "Tanchoi Silk",
    "Tissue",
    "Tripura Silk",
    "Tussar",
    "Tussar Silk",
    "Twill Net",
    "Vayal",
    "Velvet",
    "Vichitra Silk",
    "Viscose Rayon",
    "Viscose Silk",
    "Voile",
    "Wool",
    "Zamato",
}
