MYSMME_ALLOWED_FABRIC_COMPOSITION = {
    "100% Acrylic",
    "100% Cotton",
    "100% Linen",
    "100% Nylon",
    "100% Polyamide",
    "100% Polyester",
    "100% Rayon",
    "100% Silk",
    "100% Viscose",
    "100% Wool",
    "Acrylic Blend",
    "Cotton Blend",
    "Linen Blend",
    "Nylon Blend",
    "Polyamide Blend",
    "Polyester Blend",
    "Rayon Blend",
    "Silk Blend",
    "Viscose Blend",
    "Wool Blend",
}
