MYSMME_ALLOWED_ORNAMENTATION = {
    "Aari Work",
    "Applique",
    "Beads & Stones",
    "Brocade",
    "Brooch",
    "Chikankari",
    "Cutwork",
    "Dabka Work",
    "Embroidery",
    "Frills",
    "Gota Work",
    "Kaantha",
    "Kashti Work",
    "Kundan",
    "Lace",
    "Maggam Work",
    "Mirror Work",
    "Mukaish",
    "Not Applicable",
    "Patchwork",
    "Pearl Work",
    "Pintucks",
    "Pom-Pom",
    "Ruffle",
    "Sequins",
    "Stone Work",
    "Tassels and Latkans",
    "Thread Work",
    "Zardozi",
}
