MYSMME_ALLOWED_PRINT_OR_PATTERN_TYPE = {
    "Abstract",
    "Ajrakh",
    "Animal",
    "Aztec",
    "Bagh",
    "Bagru Print",
    "Bandhani",
    "Batik",
    "Block Print",
    "Botanical",
    "Butterfly",
    "Checked",
    "Chevron",
    "Digital Print",
    "Elephant",
    "Ethnic Motif",
    "Floral",
    "Foil Print",
    "Geometric",
    "Gradient",
    "Graphic",
    "Hand Painted",
    "Hazar Buti",
    "Ikat",
    "Kalamkari",
    "Leheriya",
    "Leopard",
    "Madhubani",
    "Muggu",
    "Newspaper Print",
    "Paisley",
    "Peacock",
    "Phulkari",
    "Polka Dot",
    "Scenic",
    "Shibori",
    "Solid",
    "Tie and Dye",
    "Tiger",
    "Tribal",
    "Warli",
    "Zebra",
}
