MYSMME_ALLOWED_TECHNIQUE = {
    "Assam Silk",
    "Baluchari",
    "Banarasi",
    "Bandhani",
    "Begumpuri",
    "Belt Saree",
    "Bishnupuri",
    "Bollywood",
    "Bomkai/Sonepuri",
    "Cape Saree",
    "Chettinad",
    "Cowdial Sarees",
    "Darbari",
    "Dhavani",
    "Dhoti Saree",
    "Gadhwal",
    "Gadwal",
    "Garad",
    "Gharchola",
    "Half and Half",
    "Holographic Saree",
    "Ikat",
    "Ilkal",
    "Jacket/Koti Saree",
    "Jamdani",
    "Kanjeevaram",
    "Kasavu",
    "Kashmiri",
    "Katan",
    "Kathpadar",
    "Khasi Jainsem Saree",
    "Konrad And Mubbhagam",
    "Kotki",
    "Langa Voni",
    "Lehenga Saree",
    "Leheriya",
    "Maheshwari",
    "Mangalagiri",
    "Manipuri",
    "Mekhela Chador",
    "Mysore Silk",
    "Narayan Peth",
    "Nauvari",
    "Paithani",
    "Palazzo Saree",
    "Panetar",
    "Pasapalli",
    "Patola",
    "Pochampally",
    "Ready to Wear",
    "Ruffle Saree",
    "Sambalpuri",
    "Sambhalpuri",
    "Sungudi",
    "Taant",
    "Tangail",
    "Tripura Silk",
    "Upada Pattu",
    "Venkatgiri",
}
