MEESHO_HEADERS = [
    "Fields + Description:",
    "ERROR STATUS",
    "ERROR MESSAGE",
    "Product Name",
    "Variation",
    "Meesho Price",
    "Wrong/Defective Returns Price",
    "MRP",
    "GST %",
    "HSN ID",
    "Net Weight (gms)",
    "Inventory",
    "Country of Origin",
    "Manufacturer Name",
    "Manufacturer Address",
    "Manufacturer Pincode",
    "Packer Name",
    "Packer Address",
    "Packer Pincode",
    "Importer Name",
    "Importer Address",
    "Importer Pincode",
    "Blouse",
    "Border",
    "Color",
    "Generic Name",
    "Net Quantity (N)",
    "Print or Pattern Type",
    "Saree Fabric",
    "Transparency",
    "Type",
    "Blouse Length Size",
    "Saree Length Size",
    "Image 1 (Front)",
    "Image 2",
    "Image 3",
    "Image 4",
    "Product ID / Style ID",
    "SKU ID",
    "Brand Name",
    "Group ID",
    "Product Description",
    "Blouse Color",
    "Blouse Fabric",
    "Blouse Pattern",
    "Border Width",
    "Brand",
    "Loom Type",
    "Occasion",
    "Ornamentation",
    "Pallu Details",
    "Pattern",
]

GST_DEFAULT = 5
COUNTRY_OF_ORIGIN = "India"
WR_PRICE_DEDUCTION = 10
HSN_DEFAULT=5407
INVENTORY=100