MEESHO_ALLOWED_BLOUSE_FABRIC = {
    "Acrylic",
    "Art Silk",
    "Bamboo",
    "Banarasi Silk",
    "Bangalori Silk",
    "Brocade",
    "Chambray",
    "Chanderi Cotton",
    "Chanderi Silk",
    "Chiffon",
    "Cotton",
    "Cotton Blend",
    "Cotton Cambric",
    "Cotton Linen",
    "Cotton Silk",
    "Cotton Slub",
    "Crepe",
    "Denim",
    "Dola Silk",
    "Dupion Silk",
    "Eri Silk",
    "Georgette",
    "Italian Silk",
    "Jacquard",
    "Jute Cotton",
    "Jute Khadi",
    "Jute Silk",
    "Kanjeevaram Silk",
    "Khadi Cotton",
    "Khadi Silk",
    "Khan",
    "Kora Muslin",
    "Kota Doria Cotton",
    "Kota Doria Silk",
    "Lace",
    "Linen",
    "Linen Blend",
    "Litchi Silk",
    "Lycra",
    "Lycra Blend",
    "Malai Silk",
    "Muga Silk",
    "Mulberry Silk",
    "Mulmul",
    "Muslin",
    "Mysore Silk",
    "Net",
    "No Blouse",
    "Nylon",
    "Organza",
    "Paper Silk",
    "Pashmina",
    "Poly Blend",
    "Poly Chiffon",
    "Poly Crepe",
    "Poly Georgette",
    "Poly Silk",
    "Polycotton",
    "Polyester",
    "Rayon",
    "Rayon Slub",
    "Sana Silk",
    "Satin",
    "Satin Silk",
    "Shantoon",
    "Silk",
    "Silk Blend",
    "Soft Silk",
    "Super Net",
    "Suti",
    "Synthetic",
    "Synthetic Crepe",
    "Taant",
    "Taffeta Silk",
    "Tissue",
    "Tussar",
    "Tussar Silk",
    "Twill Net",
    "Velvet",
    "Vichitra Silk",
    "Viscose",
    "Viscose Rayon",
    "Viscose Silk",
    "Voile",
    "Wool",
}
