MEESHO_ALLOWED_ORNAMENTATION = {
    "Aari Work",
    "Applique",
    "Beads & Stones",
    "Brocade",
    "Brooch",
    "Cutwork",
    "Embroidered",
    "Frills",
    "Gota Work",
    "Jacquard",
    "Kundan",
    "Lace border",
    "Maggam Work",
    "Mirror Work",
    "Mukaish",
    "Not Applicable",
    "Patchwork",
    "Pintucks",
    "Pom - Pom",
    "Pom-Pom",
    "Ruffle",
    "Sequinned",
    "Tassels and Latkans",
    "Zardozi",
}
