MEESHO_ALLOWED_SAREE_FABRIC = {
    "Acrylic",
    "Art Silk",
    "Aura Silk",
    "Bamboo",
    "Banarasi Silk",
    "Binny Silk",
    "Brocade",
    "Chambray",
    "Chanderi Cotton",
    "Chanderi Silk",
    "Chiffon",
    "Chinnon",
    "Cotton",
    "Cotton Blend",
    "Cotton Cambric",
    "Cotton Linen",
    "Cotton Silk",
    "Cotton Slub",
    "Crepe",
    "Denim",
    "Dola Silk",
    "Dupion Silk",
    "Eri Silk",
    "Georgette",
    "Italian Silk",
    "Jacquard",
    "Jimmy Choo",
    "Jute Cotton",
    "Jute Khadi",
    "Jute Silk",
    "Kanchi Silk",
    "Kanjeevaram Silk",
    "Khadi Cotton",
    "Khadi Silk",
    "Khan",
    "Kora Muslin",
    "Kota Doria Cotton",
    "Kota Doria Silk",
    "Lace",
    "Linen",
    "Linen Blend",
    "Litchi Silk",
    "Lycra",
    "Lycra Blend",
    "Malai Cotton",
    "Malai Silk",
    "Muga Silk",
    "Mulberry Silk",
    "Mulmul",
    "Murshidabad Silk",
    "Muslin",
    "Mysore Silk",
    "Net",
    "Net (Soft Net)",
    "Net (Supernet)",
    "Nylon",
    "Organza",
    "Paper Silk",
    "Pashmina",
    "Poly Blend",
    "Poly Chiffon",
    "Poly Crepe",
    "Poly Georgette",
    "Poly Silk",
    "Polycotton",
    "Polyester",
    "Rayon",
    "Rayon Slub",
    "Sana Silk",
    "Satin",
    "Satin Silk",
    "Shantoon",
    "Silk",
    "Silk Blend",
    "Simmer",
    "Soft Silk",
    "Super Net",
    "Suti",
    "Synthetic",
    "Synthetic Crepe",
    "Taant",
    "Taffeta Silk",
    "Tanchoi Silk",
    "Tissue",
    "Tripura Silk",
    "Tussar",
    "Tussar Silk",
    "Twill Net",
    "Vayal",
    "Velvet",
    "Vichitra Silk",
    "Viscose",
    "Viscose Rayon",
    "Viscose Silk",
    "Voile",
    "Wool",
    "Zamato",
}
