MEESHO_ALLOWED_TECHNIQUE = {
    "Assam Silk",
    "Bagh",
    "Balaton Silk",
    "Baluchari",
    "Banarasi",
    "Bandhani",
    "Bangalori Silk",
    "Begumpuri",
    "Belt Saree",
    "Bhagalpuri",
    "Bishnupuri",
    "Bollywood",
    "Bomkai/Sonepuri",
    "Brasso",
    "Cape Saree",
    "Chanderi",
    "Chettinad",
    "Chikankari",
    "Christian Bride",
    "Cowdial Sarees",
    "Crush",
    "Darbari",
    "Dhavani",
    "Dhoti Saree",
    "Durga Puja Saree",
    "Gadhwal",
    "Gadwal",
    "Garad",
    "Gharchola",
    "Hakoba",
    "Half and half",
    "Hazar Buti",
    "Holographic Saree",
    "Ikat",
    "Ilkal",
    "Irkal",
    "Irkal / Ilkal",
    "Jacket/Koti Saree",
    "Kaantha",
    "Kanjeevaram",
    "Kasavu",
    "Kasavu (Kerala Saree)",
    "Kashmiri",
    "Katan",
    "Kathpadar",
    "Khadi",
    "Khan",
    "Khasi Jainsem Saree",
    "Konrad And Mubbhagam",
    "Kota",
    "Kotki",
    "Langa Voni",
    "Lehenga Saree",
    "Leheriya",
    "Maheshwari",
    "Maheshwari Silk",
    "Mangalagiri",
    "Manipuri",
    "Marble",
    "Matka",
    "Mekhela chador",
    "Metallic",
    "Monochrome",
    "Muga Silk",
    "Muggu",
    "Mysore Silk",
    "Narayan Peth",
    "Nauvari",
    "No Type",
    "Paithani",
    "Palazzo Saree",
    "Panetar",
    "Pasapalli",
    "Patola",
    "Pochampally",
    "Ready to Wear",
    "Ruffle Saree",
    "Sambhalpuri",
    "Sana Silk",
    "Shaded",
    "Shimmer",
    "Sungudi",
    "Swastik",
    "Taant",
    "Tangail",
    "Tripura Silk",
    "Tussar",
    "Two-Tone",
    "Upada Pattu",
    "Venkatgiri",
    "jamdani",
}
