SNAPDEAL_ALLOWED_BLOUSE_FABRIC = {
    "Acrylic",
    "Art Silk",
    "Banarasi Silk",
    "Bangalore Silk",
    "Brasso",
    "Brocade",
    "Chanderi",
    "Chiffon",
    "Cotton",
    "Cotton Blend",
    "Crepe",
    "Crochet",
    "Georgette",
    "Jacquard",
    "Jute",
    "Lace",
    "Linen",
    "Lycra",
    "Net",
    "Not Applicable",
    "Nylon",
    "Organza",
    "Polyester",
    "Poplin",
    "Rayon",
    "Satin",
    "Silk",
    "Silk Blend",
    "Taffeta Silk",
    "Tissue",
    "Tussar",
    "Velvet",
    "Viscose",
    "Viscose Rayon",
    "Shimmer",
}
