SNAPDEAL_ALLOWED_BORDER = {
    "Block printed",
    "Digital Printed",
    "Embellished",
    "Embroidered",
    "Floral",
    "Kantha Work",
    "Lace",
    "Mirror Work",
    "None",
    "Plain",
    "Printed",
    "Sequined",
    "Stone work",
    "Woven Design",
    "Zardosi work",
    "Zari Work",
    "Cut work",
}
