SNAPDEAL_ALLOWED_COLORS = {
    "Aqua Blue",
    "Beige",
    "Beige1",
    "Black",
    "Blue",
    "Bronze",
    "Brown",
    "Burgundy",
    "Charcoal",
    "Coffee",
    "Coffee Brown",
    "Coral",
    "Cream",
    "Dark Grey",
    "Fluorescent Green",
    "Fluorescent Orange",
    "Fluorescent Pink",
    "Fuchsia",
    "Gold",
    "Green",
    "Grey",
    "Grey Melange",
    "Indigo",
    "Khaki",
    "Lavender",
    "Light Blue",
    "Light Green",
    "Light Grey",
    "LightBLue",
    "LightGreen",
    "Lime Green",
    "Lime Green1",
    "Magenta",
    "Maroon",
    "Mauve",
    "Mint Green",
    "Multicolor",
    "Multicolor 1",
    "Multicolor 2",
    "Multicolor 3",
    "Multicolor 4",
    "Multicolor 5",
    "Multicolor 6",
    "Multicolor 7",
    "Multicolor 8",
    "Multicolor 9",
    "Multicolor 10",
    "Multicolor 11",
    "Multicolor 12",
    "Multicolor 13",
    "Multicolor 14",
    "Multicolor 15",
    "Multicolor 16",
    "Multicolor 17",
    "Multicolor 18",
    "Multicolor 19",
    "Multicolor 20",
    "Mustard",
    "Navy Blue",
    "Nude",
    "Off White",
    "Olive",
    "Orange",
    "Peach",
    "Pink",
    "Purple",
    "Rama",
    "Rani",
    "Red",
    "Rose Gold",
    "Rust",
    "Sea Green",
    "Silver",
    "Sky Blue",
    "Tan",
    "Teal",
    "Turquoise",
    "White",
    "Wine",
    "Yellow",
    "Yellow1",
}
