SNAPDEAL_ALLOWED_PRINT_OR_PATTERN_TYPE = {
    "Abstract",
    "Ajrakh",
    "Animal",
    "Bagru",
    "Bagru Print",
    "Baluchari",
    "Bandhani",
    "Bandhej",
    "Batik",
    "Beads and Stones",
    "Birds",
    "Block",
    "Block Print",
    "Brand Logo",
    "Buta",
    "Camouflage",
    "Checked",
    "Chevron",
    "Chikankari",
    "Colorblock",
    "Digital Printed",
    "Embossed",
    "Ethnic Motif",
    "Ethnic Motifs",
    "Floral",
    "Foil",
    "Geometric",
    "Gotta Patti",
    "Graphic",
    "Humor & Comic",
    "Ikat",
    "Indigo",
    "Jamawar",
    "Kalamkari",
    "Kantha Work",
    "Kasavu",
    "Leheria",
    "Madhubani",
    "Mirror Work",
    "Music",
    "Nature",
    "Ombre",
    "Paisely",
    "Paisley",
    "PatchWork",
    "Patola",
    "People",
    "Phulkari",
    "Pochampally",
    "Polka Dots",
    "Religious",
    "Sambalpuri",
    "Sequined",
    "Solid",
    "Striped",
    "Superhero",
    "Textured",
    "Thread Work",
    "Tie & Dye",
    "Tribal",
    "Typography",
    "Warli Art",
    "Zardorsi",
    "Zari Work",
}
