SNAPDEAL_ALLOWED_SAREE_FABRIC = {
    "Art Silk",
    "Asaam Silk",
    "Bangalore Silk",
    "Brasso",
    "Brocade",
    "Chanderi",
    "Chiffon",
    "Cotton",
    "Cotton Blend",
    "Cotton Silk",
    "Crepe",
    "Georgette",
    "Jacquard",
    "Jimmy Choo",
    "Jute",
    "Linen",
    "Lycra",
    "Net",
    "Nylon",
    "Organza",
    "Polyester",
    "Rayon",
    "Satin",
    "Shimmer",
    "Silk",
    "Silk Blend",
    "Synthetic",
    "Taffeta",
    "Tissue",
    "Velvet",
    "Viscose",
}
