SNAPDEAL_ALLOWED_TECHNIQUE = {
    "Baluchari Saree",
    "Banarasi saree",
    "Bandhani Sarees",
    "Bhagalpuri Saree",
    "Bomkai Saree",
    "Chanderi saree",
    "Chettinad Saree",
    "Chikankari Saree",
    "Coorgi Saree",
    "Dharmavaram Saree",
    "Foam Saree",
    "Goan Kunbi Saree",
    "Ilkal Saree",
    "Jamdani Saree",
    "Kanjeevaram Sarees",
    "Kasavu Saree",
    "Kashmiri Kani Saree",
    "Kota Doria Saree",
    "Leheriya Saree",
    "Maheshwari Saree",
    "Mangalgiri Saree",
    "Mashru Saree",
    "Mekhela Chador",
    "Muga Silk Saree",
    "Mysore Silk Sarees",
    "Narayanpet Saree",
    "Paithani Sarees",
    "Pashmina Saree",
    "Patola Saree",
    "Phulkari saree",
    "Pochampally Ikkat Saree",
    "Ready To Wear Saree",
    "Regular Saree",
    "Sambalpuri Saree",
    "Tant Saree",
    "Uppada saree",
    "Venkatagiri Saree",
}
