MEESHO_ALLOWED_COLORS = {
    "Aqua Blue",
    "Baby Blue",
    "Beige",
    "Black",
    "Blue",
    "Bronze",
    "Brown",
    "Copper",
    "Coral",
    "Cream",
    "Dark Pink",
    "Gajari",
    "Gold",
    "Green",
    "Grey",
    "Grey Melange",
    "Indigo",
    "Khaki",
    "Lavender",
    "Lemon Yellow",
    "Maroon",
    "Mehendi",
    "Metallic",
    "Mint Green",
    "Multicolor",
    "Mustard",
    "Navy Blue",
    "Nude",
    "Olive",
    "Orange",
    "Pastel Blue",
    "Pastel Brown",
    "Pastel Orange",
    "Pastel Pink",
    "Pastel Red",
    "Pastel Yellow",
    "Peach",
    "Pink",
    "Purple",
    "Rama",
    "Rani",
    "Red",
    "Rust",
    "Sage",
    "Silver",
    "Sky Blue",
    "Teal",
    "Tricolor",
    "Turquoise",
    "White",
    "Yellow",
}
