MEESHO_ALLOWED_PRINT_OR_PATTERN_TYPE = {
    "Abstract",
    "Ajrakh",
    "Animal",
    "Applique",
    "Aztec",
    "Bagru Print",
    "Bandhani",
    "Batik",
    "Block",
    "Bohemian",
    "Boho Saree",
    "Botanical",
    "Butterfly",
    "Checked",
    "Chevron",
    "Colorblocked",
    "Elephant",
    "Embellished",
    "Ethnic Motif",
    "Floral",
    "Foil",
    "Geometric",
    "Gradient",
    "Graphic",
    "Hand Painted",
    "Herringbone",
    "Houndstooth",
    "Ikat",
    "Kalamkari",
    "Leheriya",
    "Leopard",
    "Madhubani",
    "Micro",
    "Moti Work",
    "Nath",
    "Newspaper Print",
    "Paisley",
    "Peacock",
    "Phulkari",
    "Polka Dot",
    "Quirky",
    "Ribbon",
    "Scenic",
    "Shibori",
    "Solid",
    "Stripe",
    "Tie and Dye",
    "Tiger",
    "Tribal",
    "Warli",
    "Woven Design",
    "Zari Woven",
    "Zari butta",
    "Zebra",
}
